Update Superstaq target assertion in daily integration tests (+ workflow updates) (#1394)
Closes: https://github.com/Infleqtion/client-superstaq/issues/1393

This PR makes the target assertion less strict due to dynamic fields
like the target's availability. E.g.,
```bash
>           assert target == unfiltered_targets[target.target], (
                f"Divergent targets.\nFiltered: {target!r}\n"
                f"Unfiltered: {unfiltered_targets[target.target]!r}"
            )
E           AssertionError: Divergent targets.
E             Filtered: Target(target='qtm_helios-1_qpu', supports_submit=True, supports_submit_qubo=False, supports_compile=True, available=False, retired=False, accessible=True)
E             Unfiltered: Target(target='qtm_helios-1_qpu', supports_submit=True, supports_submit_qubo=False, supports_compile=True, available=True, retired=False, accessible=True)
E           assert Target(target...cessible=True) == Target(target...cessible=True)
E             
E             Full diff:
E             - Target(target='qtm_helios-1_qpu', supports_submit=True, supports_submit_qubo=False, supports_compile=True, available=True, retired=False, accessible=True)
E             ?                                                                                                                      ^^^
E             + Target(target='qtm_helios-1_qpu', supports_submit=True, supports_submit_qubo=False, supports_compile=True, available=False, retired=False, accessible=True)
E             ?    
```


This PR also makes it so the issue creation job does not trigger for
manually dispatched workflows and also makes the job a dependent,
separate job to ensure multiple issues aren't created for each failed
sub-workflow in the matrix strategy.

---------

Signed-off-by: Bharath <bharath.thotakura@infleqtion.com>